#!/usr/bin/env bash

rename_patch () {
  tmp=$(foamDictionary constant/polyMesh/boundary -entry entry0.${1} -value)
  foamDictionary constant/polyMesh/boundary -entry entry0.${1} -remove
  foamDictionary constant/polyMesh/boundary -entry entry0.${2} -set "${tmp}"
}

foamCleanPolyMesh
cgnsToFoam ../../../../geometries/geometries/dns_channel_halfslab.cgns 
splitByRegion -noDict -patch "xm-periodic"

mirrorMesh -overwrite
cleanUpMirroredMesh -overwrite
combinePatchFaces 90 -overwrite
transformPoints -scale 1000 
transformPoints -translate "(0 2 0)"

foamDictionary constant/polyMesh/boundary -entry entry0.zm-symmetry -remove
splitByRegion -noDict -patch "zp-symmetry"

rename_patch "ym-wall" "ym"
rename_patch "yp-wall" "yp"
rename_patch "xm-periodic1" "xm"
rename_patch "xm-periodic3" "xp"
rename_patch "zp-symmetry1" "zp"
rename_patch "zp-symmetry3" "zm"

renumberCoupledPatches -overwrite

entry="foamDictionary constant/polyMesh/boundary -entry entry0"


${entry}.xm.type -set "cyclic"
${entry}.xm.inGroups -set "1(cycylic)"
${entry}.xm.matchTolerance -set "0.0001"
${entry}.xm.transform -set "translational"
${entry}.xm.separationVector -set "(6.28318530718 0 0)"
${entry}.xm.neighbourPatch -set "xp"

${entry}.xp.type -set "cyclic"
${entry}.xp.inGroups -set "1(cycylic)"
${entry}.xp.matchTolerance -set "0.0001"
${entry}.xp.transform -set "translational"
${entry}.xp.separationVector -set "(-6.28318530718 0 0)"
${entry}.xp.neighbourPatch -set "xm"


${entry}.zm.type -set "cyclic"
${entry}.zm.inGroups -set "1(cycylic)"
${entry}.zm.matchTolerance -set "0.0001"
${entry}.zm.transform -set "translational"
${entry}.zm.separationVector -set "(0 0 3.1415926535)"
${entry}.zm.neighbourPatch -set "zp"

${entry}.zp.type -set "cyclic"
${entry}.zp.inGroups -set "1(cycylic)"
${entry}.zp.matchTolerance -set "0.0001"
${entry}.zp.transform -set "translational"
${entry}.zp.separationVector -set "(0 0 -3.1415926535)"
${entry}.zp.neighbourPatch -set "zm"


renumberMesh -overwrite

checkMesh
